version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - CHROME_BIN=/usr/bin/chromium-browser
    volumes:
      - ./pw-browsers:/app/pw-browsers
    restart: unless-stopped
    # Add necessary capabilities for Chrome
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined

volumes:
  postgres_data: 