[build]
builder = "DOCKERFILE"
dockerfilePath = "dockerfile"

[deploy]
startCommand = "node dist/main"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 